### ISSUE TITLE
Magento x Izipizi x Merchant Onboarding

### ISSUE THREAD

**Issue by PriyankaAggarwal23** [pointspay/pointspay-magento#2]
**Earlier issue:** Merchant was getting error “something went wrong" on staging environment while fetching payment methods. 
**Solution:**  As a temporary workaround, merchant overridden the templates generating the calls to remove the payload data that wasn’t needed and caused the error.

**Current issue:** Merchant observed that the Flying Blue+ Payment method disappears from the Magento Back Office every time something is deployed on the staging environment. 
**Merchant's feedback reg this issue**: I can see that when I click the "Fetch payment methods" in the Back Office, a file is downloaded inside pub/media/pointspay and filled with the payments method fields, including Flying Blue. When we deploy, that file gets replaced and we end up with no payment methods configured.

Here is what the file looks like after a deploy on the server:
$ cat pub/media/pointspay/pointspay_methods.xml
<?xml version="1.0"?>
<payment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="urn:magento:module:Pointspay_Pointspay:etc/pointspay_methods.xsd">
    <pointspay_methods>
    </pointspay_methods>
</payment>

After a quick investigation it looks like the pub file gets replaced by the vendor/pointspay/pointspay-magento/etc/pointspay_methods.xml template file on every deployment.
The problem seems to come from \Pointspay\Pointspay\Service\PaymentMethodsUpdater\FileResolver::get, where the template file gets copied into the pub directory if it is not found. It looks like the file is never found even though it already exists.

**Comment by DamjanLogeecom** [comment]
Hey @PriyankaAggarwal23,

Please note that the same [ticket](https://pointspay.atlassian.net/browse/MI-5) was created by Abigail on Jira last week.

Our team responded with the following:

_Hey,

Our team checked this issue and based on the description we can conclude that the issue will be fixed with the new plugin version. 
The new plugin version uses a shop database for storing available payment methods when a merchant clicks on the refresh button.

Best regards._

Can you confirm that they upgraded to the new plugin version?

Thank you!

**Comment by vlaskinvlad** [comment]
reopen it later
